version: '3'

services:
  db:
    environment:
      POSTGRES_USER: ${POSTGRES_ZE_USER_API_DEV}
      POSTGRES_PASSWORD: ${POSTGRES_ZE_PASSWORD_API_DEV}
      POSTGRES_DB: ${POSTGRES_ZE_DB_API_DEV}
    container_name: ze-db
    image: mdillon/postgis
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  api:
    build:
      context: .
    container_name: ze-api
    ports:
      - "5000:5000"
    volumes:
      - ./application:/application
      - ./alembic:/alembic
    depends_on:
      - db
    env_file: .env
    networks:
      - default
    restart: always