"""Add table partner

Revision ID: f1215e1bc1d5
Revises: 
Create Date: 2020-08-11 00:15:44.871750

"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f1215e1bc1d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trading_name', sa.String(length=128), nullable=False),
    sa.Column('owner_name', sa.String(length=128), nullable=False),
    sa.Column('document', sa.String(length=18), nullable=False),
    sa.Column('address', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('coverage_area', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document')
    )
    op.create_index(op.f('ix_partner_address'), 'partner', ['address'], unique=False)
    op.create_index(op.f('ix_partner_coverage_area'), 'partner', ['coverage_area'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_coverage_area'), table_name='partner')
    op.drop_index(op.f('ix_partner_address'), table_name='partner')
    op.drop_table('partner')
    # ### end Alembic commands ###
